name: Comment PR

on:
  pull_request_target:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  comment-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx chachalog@0.4 comment-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
