name: Release

on:
  push:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write # Used for authentication with JSR
    steps:
      - uses: actions/checkout@v4
      - uses: pkgxdev/dev@v0
      - run: yarn install --immutable
      - name: Create release PR or publish packages
        uses: changesets/action@v1
        with:
          title: "chore: release packages"
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
