name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  prepare-next-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx chachalog@0.3 prepare-next-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pkgxdev/dev@v1
      - name: Build and publish
        run: |
          just build
          yarn config set npmAuthToken '${{ secrets.NPM_TOKEN }}'
          yarn workspaces foreach -Avv --no-private npm publish --access public --tolerate-republish --provenance
          yarn dlx --quiet jsr publish --allow-dirty
      - run: npx chachalog@0.3 publish-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
